import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar_scrollIncidator from "../app/components/Sidebar_scrollIncidator/Sidebar_scrollIncidator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Header />
        <main className="flex gap-5 mx-5 pb-5"   style={{ height: "calc(100vh - 120px)" }}>
          <Sidebar_scrollIncidator />
        {children}</main>
      </body>
    </html>
  );
}
